### ISSUE TITLE
Issuer content is missing

### ISSUE THREAD

**Issue by flyerhzm** [Prepsmith/eic-redash#1]
saml response from redash is

```
<?xml version='1.0' encoding='UTF-8'?>
<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="http://localhost:5000/saml/callback" Destination="https://login.staging.prepsmith.com/saml/auth" ID="id-1nIklwdRC8rDFZjMn" IssueInstant="2018-01-11T09:19:19Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0">
  <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" />
  <samlp:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
</samlp:AuthnRequest>
```

content of saml:Issuer is missing, it could be SAML Entity ID in the setting, but I can't change it.

I have to hack saml-idp https://github.com/Prepsmith/saml_idp/commit/842e196a52ccc0947227c7785519b68c60a0c96d

**Comment by apetitdev** [comment]
@flyerhzm I am not sure but I think we can change it. Maybe we can discuss about that this morning.

**Comment by apetitdev** [comment]
@gabpaquin I am not sure we shouldn't fix these issues. Richard made a hack to make it work in customer api side but this should be at least need a look.
